---
- name: Ensure folders are available
  ansible.builtin.file:
    path: "{{ gitea_filesystem_root }}/{{ item }}"
    state: "directory"
    mode: 0700
  with_items:
    - data

- name: Ensure latest gitea image version
  community.docker.docker_image:
    name: "{{ gitea_image_name }}"
    tag: "{{ gitea_image_tag }}"
    state: present
    source: pull
    force_source: true

- name: Ensure gitea container running
  community.docker.docker_container:
    name: "{{ gitea_container_name }}"
    image: "{{ gitea_image_name }}:{{ gitea_image_tag }}"
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ gitea_filesystem_root }}/data:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    published_ports:
      - "{{ gitea_config_http_port }}:3000"
      - "{{ gitea_config_sshd_port }}:22"
