---
- name: ensure folders are available
  file:
    path: "{{ gitea_filesystem_root }}/{{ item }}"
    state: "directory"
  with_items:
    - data

- name: ensure latest gitea image version
  docker_image:
    name: "{{ gitea_image_name }}"
    tag: "{{ gitea_image_tag }}"
    state: present
    source: pull
    force_source: yes

- name: ensure gitea container running
  docker_container:
    name: "{{ gitea_container_name }}"
    image: "{{ gitea_image_name }}:{{ gitea_image_tag }}"
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ gitea_filesystem_root }}/data:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    published_ports:
      - "{{ gitea_config_sshd_port }}:3000"
      - "{{ gitea_config_http_port }}:22"
